### ISSUE TITLE
Doesn't seem to work with libraries in the user library directory on windows

### ISSUE THREAD

**Issue by Loki44** [NascentMaker/scadi#42]
**Describe the bug**

The tool fails to inline libraries that are in the SCAD user library directory (C:\Users\<user>\Documents\OpenSCAD\libraries)

**To Reproduce**

1. install BOLS in user scad library
2. create an scad file with the only line "include <BOSL2/std.scad>;"
3. run scadi
4. inlined file is empty

**Additional context**

It does successfully inline files that are in the same directory as the target file.

**Comment by tbjers** [comment]
Thank you for reporting this. I will look into adding library folder detection. Initially, I avoided this since it requires special handling for different operating systems.

**Comment by Loki44** [comment]
It's working great, thanks.

In-lining a large library like BOSL2 seems to cause SCAD to hit a recursion limit, but I'm guessing that's an openSCAD bug/limitation rather than anything to do with your tool.

(I've attached the test file, and in-lined version, in case you wanted to see it)

[hex-grid-test.txt](https://github.com/NascentMaker/scadi/files/11171723/hex-grid-test.txt)
[inline-hex-grid-test.txt](https://github.com/NascentMaker/scadi/files/11171726/inline-hex-grid-test.txt)

**Comment by tbjers** [comment]
@Loki44 I tested this on my development server and can reproduce your results. This would be considered a bug, so I will create a new issue you can track.

**Comment by tbjers** [comment]
Inlining confirmed to work with the user's Documents folder.

**Comment by tbjers** [comment]
@Loki44 I have created a new issue for the OpenSCAD error: #51.
